AlreadyCheckedOutBranch = "Już przęłączono na tą gałąź"
BranchName = "Nazwa gałęzi"
BranchesTitle = "Gałęzie"
CannotGitAdd = "Nie można git add --patch nieśledzonych plików"
CantCloseConfirmationPrompt = "Nie można zamknąć monitu potwierdzenia: {{.error}}"
CantDeleteCheckOutBranch = "Nie możesz usunąć obecnej przełączonej gałęzi!"
CantFixupWhileUnstagedChanges = "Nie można wykonać naprawy, kiedy istnieją niezatwierdzone zmiany"
CantIgnoreTrackFiles = "Nie można zignorować nieśledzonych plików"
CantMergeBranchIntoItself = "Nie możesz scalić gałęzi do samej siebie"
ClearFilePanel = "Wyczyść panel plików"
CloseConfirm = "{{.keyBindClose}}: zamknij, {{.keyBindConfirm}}: potwierdź"
CommitChanges = "commituj zmiany"
CommitMessage = "Wiadomość commita"
CommitWithoutMessageErr = "Nie możesz commitować bez podania wiadomości"
CommitsTitle = "Commity"
DeleteBranch = "Usuń gałąź"
DeleteBranchMessage = "Jesteś pewien, że chcesz usunąć gałąź {{.selectedBranchName}} ?"
DiffTitle = "Różnice"
EditConfig = "edit config file"
Error = "Błąd"
FileHasNoUnstagedChanges = "Plik nie zawiera żadnych nieopublikowanych zmian do dodania"
FileNoMergeCons = "Ten plik nie powoduje konfliktów scalania"
FilesTitle = "Pliki"
Fixup = "Napraw"
ForceCheckoutBranch = "Wymuś przełączenie gałęzi"
ForceDeleteBranchMessage = "Are you sure you want to force delete the branch {{.selectedBranchName}}?"
ForcePush = "Force push"
ForcePushPrompt = "Your branch has diverged from the remote branch. Press 'esc' to cancel, or 'enter' to force push."
IssntListOfViews = "{{.name}} nie jest na liście widoków"
MergeAborted = "Scalanie anulowane"
NewBranchNameBranchOff = "Nazwa nowej gałęzi (gałąź na bazie {{.branchName}})"
NoBranchesThisRepo = "Brak gałęzi dla tego repozytorium"
NoChangedFiles = "Brak zmienionych plików"
NoCommitsThisBranch = "Brak commitów dla tej gałęzi"
NoFilesDisplay = "Brak pliku do wyświetlenia"
NoStagedFilesToCommit = "Brak zatwierdzonych plików do commita"
NoStashEntries = "Brak pozycji w schowku"
NoStashTo = "Brak schowka dla {{.method}}"
NoTrackedStagedFilesStash = "Nie masz śledzonych/zatwierdzonych plików do przechowania"
NoTrackingThisBranch = "Brak śledzenia dla tej gałęzi"
NoViewMachingNewLineFocusedSwitchStatement = "Brak widoku pasującego do instrukcji przełączania newLineFocused"
NotEnoughSpace = "Za mało miejsca do wyświetlenia paneli"
OnlyRenameTopCommit = "Można przmianować tylko najwyższy commit"
OnlySquashTopmostCommit = "Można tylko ścisnąć najwyższy commit"
OpenConfig = "open config file"
PotentialErrInGetselectedCommit = "potencjalny błąd w getSelected Commit (niedopasowane ui i stan)"
PullWait = "Wciąganie zmian..."
PushWait = "Wypychanie zmian..."
RenameCommit = "Przemianuj commit"
ResetToCommit = "Zresetuj, aby commitować"
RunningSubprocess = "uruchomiony podproces"
StashChanges = "Przechowaj zmiany"
StashDrop = "Porzuć schowek"
StashTitle = "Schowek"
StatusTitle = "Status"
SureDropStashEntry = "Jesteś pewny, że chcesz porzucić tę pozycję w schowku?"
SureFixupThisCommit = "Jesteś pewny, ze chcesz naprawić ten commit? Commit poniżej zostanie ściśnięty w górę wraz z tym"
SureForceCheckout = "Jesteś pewny, że chcesz wymusić przełączenie? Stracisz wszystkie lokalne zmiany"
SureResetHardHead = "Jesteś pewny, że chcesz wykonać `reset --hard HEAD`? Możesz stracić wprowadzone zmiany"
SureResetThisCommit = "Jesteś pewny, że chcesz zresetować ten commit?"
SureTo = "Jesteś pewny, że chcesz {{.deleteVerb}} {{.fileName}} (stracisz swoje wprowadzone zmiany)?"
YouNoCommitsToSquash = "Nie masz commitów do ściśnięcia"
abortMerge = "o scalaniu"
addPatch = "dodaj łatkę"
apply = "zastosuj"
checkout = "przełącz"
checkoutByName = "przełącz używając nazwy"
delete = "usuń"
deleteBranch = "usuń gałąź"
drop = "porzuć"
edit = "edytuj"
fixupCommit = "napraw commit"
forceCheckout = "wymuś przełączenie"
forceDeleteBranch = "delete branch (force)"
ignore = "ignoruj"
merge = "scal"
navigate = "nawiguj"
navigateConflicts = "nawiguj konflikty"
newBranch = "nowa gałąź"
newFocusedViewIs = "nowy skupiony widok to {{.newFocusedView}}"
open = "otwórz"
pickBothHunks = "wybierz oba kawałki"
pickHunk = "wybierz kawałek"
pop = "wyciągnij"
refresh = "odśwież"
rename = "przemianuj"
resetToThisCommit = "zresetuj do tego commita"
resizingPopupPanel = "skalowanie wyskakującego panelu"
resolveMergeConflicts = "rozwiąż konflikty scalania"
scroll = "przewiń"
selectHunk = "wybierz kawałek"
settingPreviewsViewTo = "ustawianie poprzedniego widoku na: {{.oldViewName}}"
squashDown = "ściśnij w dół"
stashFiles = "przechowaj pliki"
toggleStaged = "przełącz zatwierdzenie"
undo = "cofnij"
