name: Check Required PR Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled]

jobs:
  check-required-pr-label:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "ignore-for-release, feature, enhancement, bug, maintenance, docs, i18n, performance"
